[project]
org-name= "yashodperera"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.18"
    path = "./dependencies/mysql-connector-java-8.0.18.jar"
    groupId = "mysql"
    modules = ["manageStudents"]